# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name='messages.proto',
    package='messages',
    syntax='proto3',
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0emessages.proto\x12\x08messages\"H\n\x0b\x43lientHello\x12\r\n\x05nonce\x18\x01 \x01(\x0c\x12\x11\n\tkey_share\x18\x02 \x01(\x0c\x12\x17\n\x0fshare_signature\x18\x03 \x01(\x0c\"/\n\x0bServerHello\x12\r\n\x05nonce\x18\x01 \x01(\x0c\x12\x11\n\tkey_share\x18\x02 \x01(\x0c\"$\n\x0fVerifyIntegrity\x12\x11\n\tintegrity\x18\x01 \x01(\x0c\"A\n\rEncryptedData\x12\n\n\x02iv\x18\x01 \x01(\x0c\x12\x11\n\tencrypted\x18\x02 \x01(\x0c\x12\x11\n\tintegrity\x18\x03 \x01(\x0c\"\\\n\x06Status\x12\x0f\n\x07message\x18\x03 \x01(\t\x12%\n\x05state\x18\x04 \x01(\x0e\x32\x16.messages.Status.State\"\x1a\n\x05State\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x32\xcf\x01\n\x06Server\x12\x43\n\x11InitiateHandshake\x12\x15.messages.ClientHello\x1a\x15.messages.ServerHello\"\x00\x12\x43\n\tIntegrity\x12\x19.messages.VerifyIntegrity\x1a\x19.messages.VerifyIntegrity\"\x00\x12;\n\x0cTransferData\x12\x17.messages.EncryptedData\x1a\x10.messages.Status\"\x00\x62\x06proto3'
)


_STATUS_STATE = _descriptor.EnumDescriptor(
    name='State',
    full_name='messages.Status.State',
    filename=None,
    file=DESCRIPTOR,
    create_key=_descriptor._internal_create_key,
    values=[
        _descriptor.EnumValueDescriptor(
            name='OK', index=0, number=0,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key),
        _descriptor.EnumValueDescriptor(
            name='ERROR', index=1, number=1,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=322,
    serialized_end=348,
)
_sym_db.RegisterEnumDescriptor(_STATUS_STATE)


_CLIENTHELLO = _descriptor.Descriptor(
    name='ClientHello',
    full_name='messages.ClientHello',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='nonce', full_name='messages.ClientHello.nonce', index=0,
            number=1, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=b"",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='key_share', full_name='messages.ClientHello.key_share', index=1,
            number=2, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=b"",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='share_signature', full_name='messages.ClientHello.share_signature', index=2,
            number=3, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=b"",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=28,
    serialized_end=100,
)


_SERVERHELLO = _descriptor.Descriptor(
    name='ServerHello',
    full_name='messages.ServerHello',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='nonce', full_name='messages.ServerHello.nonce', index=0,
            number=1, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=b"",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='key_share', full_name='messages.ServerHello.key_share', index=1,
            number=2, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=b"",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=102,
    serialized_end=149,
)


_VERIFYINTEGRITY = _descriptor.Descriptor(
    name='VerifyIntegrity',
    full_name='messages.VerifyIntegrity',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='integrity', full_name='messages.VerifyIntegrity.integrity', index=0,
            number=1, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=b"",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=151,
    serialized_end=187,
)


_ENCRYPTEDDATA = _descriptor.Descriptor(
    name='EncryptedData',
    full_name='messages.EncryptedData',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='iv', full_name='messages.EncryptedData.iv', index=0,
            number=1, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=b"",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='encrypted', full_name='messages.EncryptedData.encrypted', index=1,
            number=2, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=b"",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='integrity', full_name='messages.EncryptedData.integrity', index=2,
            number=3, type=12, cpp_type=9, label=1,
            has_default_value=False, default_value=b"",
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=189,
    serialized_end=254,
)


_STATUS = _descriptor.Descriptor(
    name='Status',
    full_name='messages.Status',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='message', full_name='messages.Status.message', index=0,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='state', full_name='messages.Status.state', index=1,
            number=4, type=14, cpp_type=8, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
        _STATUS_STATE,
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=256,
    serialized_end=348,
)

_STATUS.fields_by_name['state'].enum_type = _STATUS_STATE
_STATUS_STATE.containing_type = _STATUS
DESCRIPTOR.message_types_by_name['ClientHello'] = _CLIENTHELLO
DESCRIPTOR.message_types_by_name['ServerHello'] = _SERVERHELLO
DESCRIPTOR.message_types_by_name['VerifyIntegrity'] = _VERIFYINTEGRITY
DESCRIPTOR.message_types_by_name['EncryptedData'] = _ENCRYPTEDDATA
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientHello = _reflection.GeneratedProtocolMessageType('ClientHello', (_message.Message,), {
    'DESCRIPTOR': _CLIENTHELLO,
    '__module__': 'messages_pb2'
    # @@protoc_insertion_point(class_scope:messages.ClientHello)
})
_sym_db.RegisterMessage(ClientHello)

ServerHello = _reflection.GeneratedProtocolMessageType('ServerHello', (_message.Message,), {
    'DESCRIPTOR': _SERVERHELLO,
    '__module__': 'messages_pb2'
    # @@protoc_insertion_point(class_scope:messages.ServerHello)
})
_sym_db.RegisterMessage(ServerHello)

VerifyIntegrity = _reflection.GeneratedProtocolMessageType('VerifyIntegrity', (_message.Message,), {
    'DESCRIPTOR': _VERIFYINTEGRITY,
    '__module__': 'messages_pb2'
    # @@protoc_insertion_point(class_scope:messages.VerifyIntegrity)
})
_sym_db.RegisterMessage(VerifyIntegrity)

EncryptedData = _reflection.GeneratedProtocolMessageType('EncryptedData', (_message.Message,), {
    'DESCRIPTOR': _ENCRYPTEDDATA,
    '__module__': 'messages_pb2'
    # @@protoc_insertion_point(class_scope:messages.EncryptedData)
})
_sym_db.RegisterMessage(EncryptedData)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
    'DESCRIPTOR': _STATUS,
    '__module__': 'messages_pb2'
    # @@protoc_insertion_point(class_scopes:messages.Status)
})
_sym_db.RegisterMessage(Status)


_SERVER = _descriptor.ServiceDescriptor(
    name='Server',
    full_name='messages.Server',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=351,
    serialized_end=558,
    methods=[
        _descriptor.MethodDescriptor(
            name='InitiateHandshake',
            full_name='messages.Server.InitiateHandshake',
            index=0,
            containing_service=None,
            input_type=_CLIENTHELLO,
            output_type=_SERVERHELLO,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name='Integrity',
            full_name='messages.Server.Integrity',
            index=1,
            containing_service=None,
            input_type=_VERIFYINTEGRITY,
            output_type=_VERIFYINTEGRITY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name='TransferData',
            full_name='messages.Server.TransferData',
            index=2,
            containing_service=None,
            input_type=_ENCRYPTEDDATA,
            output_type=_STATUS,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_SERVER)

DESCRIPTOR.services_by_name['Server'] = _SERVER

# @@protoc_insertion_point(module_scope)
